const { Schema, model } = require('mongoose')

module.exports = model('Purchase', new Schema({
  day_id: { ref: 'Day', type: Schema.Types.ObjectId },
  client_id: { ref: 'Client', type: Schema.Types.ObjectId },
  opened_by: { ref: 'User', type: Schema.Types.ObjectId },
  closed_by: { ref: 'User', type: Schema.Types.ObjectId },
  employee_id: { ref: 'Employee', type: Schema.Types.ObjectId },
  employee_name: { type: String },
  room_id: { ref: 'Room', type: Schema.Types.ObjectId },
  room_name: { type: String },
  service_id: { ref: 'Service', type: Schema.Types.ObjectId },
  service_name: { type: String },
  opened_at: { type: Date, default: Date.now },
  closed_at: { type: Date },
  payment_category: { type: String },
  payment_discount_reason: { type: String },
  payment_discount_reason_text: { type: String },
  payment_discount_value: { type: String },
  payment_method_id: { ref: 'Method', type: Schema.Types.ObjectId },
  payment_method_name: { type: String },
  cash_box_id: { ref: 'Cash', type: Schema.Types.ObjectId },
  cash_box_name: { type: String },
  card_id: { ref: 'Card', type: Schema.Types.ObjectId },
  card_name: { type: String },
  item_cost: { type: Number },
  item_cost_discounted: { type: Number },
  item_id: { ref: 'Bar', type: Schema.Types.ObjectId },
  item_name: { type: String },
  program_item_id: { ref: 'Program', type: Schema.Types.ObjectId },
  program_item_name: { type: String },
}))